version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: nilm_influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=anvaya
      - DOCKER_INFLUXDB_INIT_BUCKET=nilm
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=anvaya-token

  mosquitto:
    image: eclipse-mosquitto
    container_name: nilm_mqtt
    ports:
      - "1883:1883"

  redis:
    image: redis:7
    container_name: nilm_redis
    ports:
      - "6379:6379"

volumes:
  influxdb_data:
